### ISSUE TITLE
Documentation is incorrect for Django 1.7+

### ISSUE THREAD

**Issue by audiolion** [justinmayer/django-autoslug#11]
This issue has been noted on [bitbucket](https://bitbucket.org/neithere/django-autoslug/issues/29/makemigrations-fails-when-a-lambda-is-used) but still hasn't received an update. Documentation should have a warning of only working on Django <=1.6 or removed until updated documentation is created

**Comment by justinmayer** [comment]
django-autoslug v1.9.4, which should now support Django 1.10, 1.11, and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). The documentation will be updated once ownership of the corresponding ReadTheDocs project has been transferred. ([Link to transfer request](https://github.com/rtfd/readthedocs.org/issues/5216))

Thanks for your patience! 🎉
