### ISSUE TITLE
Function to generate unique slug can generate an excessive number of DB query

### ISSUE THREAD

**Issue by jpaulodit** [justinmayer/django-autoslug#14]
The code that generates the unique slug is querying the database indefinitely until it finds the unique value.

In the case of common words, this causes excessive number of db calls. It would be nice if it was possible to specify the maximum number of tries. A uuid value can be used to generate the slug after index exceeds that number.

**Comment by jpaulodit** [comment]
Added suggested fix in PR #15

**Comment by justinmayer** [comment]
Fix for this issue was proposed in above-referenced PR, but it was subsequently closed without explanation. Closing this issue until such time as someone wants to look at it again.
