### ISSUE TITLE
Migration error 'function' object has no attribute 'slugify'

### ISSUE THREAD

**Issue by vladimirnani** [justinmayer/django-autoslug#20]
Hey here is what was generated with django migrations
`from slugify import slugify`
...
`  ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from=b'name', slugify=slugify.slugify.slugify, unique=True)),`

AttributeError: 'function' object has no attribute 'slugify'

I get this when trying to migrate.

**Comment by justinmayer** [comment]
Hi Vladimir. Were you able to resolve this issue? Might you be willing to help implement a fix for it?

**Comment by vladimirnani** [comment]
Hey @justinmayer. To add more context: 
I was using it together with https://github.com/voronind/awesome-slugify

The problem was in one too many slugify's :) `slugify=slugify.slugify.slugify` 

Solution would be in either correcting path in the migration or better wrapping awesome-slugify into your own custom_slugify method.
