### ISSUE TITLE
Support for Django 1.11?

### ISSUE THREAD

**Issue by brylie** [justinmayer/django-autoslug#29]
The Cookiecutter Django project depends on this package. Currently, Cookiecutter Django is pinned to Django 1.10.x, based on an [issue to check for 1.11.x support in project dependencies](https://github.com/pydanny/cookiecutter-django/issues/1111). 

Does the django-autoslug package support Django 1.11?

**Comment by eykd** [comment]
The fixes for 1.10 on master (see #6) are working just fine for me on 1.11, however the maintainer has not released a new version since the changes were merged last October. :(

**Comment by evilplanet** [comment]
Is this still maintained?

**Comment by justinmayer** [comment]
django-autoslug v1.9.4, which should now support Django 1.10, 1.11, and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). The documentation will be updated once ownership of the corresponding ReadTheDocs project has been transferred. ([Link to transfer request](https://github.com/rtfd/readthedocs.org/issues/5216))

Thanks to everyone for your patience! 🎉
