### ISSUE TITLE
Is django-autoslug dead?

### ISSUE THREAD

**Issue by danniranderis** [justinmayer/django-autoslug#31]
Hi,

I have noticed, as many others, that this package isn't moving forward.

As mentioned in #16 @neithere doesn't have the time to maintain the project. Also mentioned is a movement of the project to jazzband, which I can see here: https://github.com/jazzband/roadies/issues/38
But, as far I can see in that issue, the move isn't completed yet. #12 tells the same story.

Cookiecutter-django are started considering abandon django-autoslug (https://github.com/pydanny/cookiecutter-django/issues/1111), and I have the same thoughts as well. If the community isn't able to help develop and maintain the project - I have to either abandon it or clone the project and try to get a movement of the community. A thing I really would not like. 

@neithere and others - are there anything we as community can do the help the movement of the project to jazzband?

**Comment by eykd** [comment]
I have to say, after following this saga for a while, it's beginning to look like a fork is going to be necessary, at least until @neithere returns from his sojourning. He's not been active on Github since July, and has ignored this project since proposing it to Jazzband in February.

The project is LGPL, a fork isn't a problem. I wonder, should you reach out to the jazzband thread and see what they would recommend? Perhaps they would be interested in facilitating a fork?

**Comment by tony** [comment]
LGPL? Ahhh why >_<

Didn't know that.

If it's going to transition, it should be BSD, MIT, Apache2, etc. Derivative clauses can really mess stuff up

**Comment by tony** [comment]
Don't fork this project. Fork https://github.com/django-extensions/django-extensions's AutoSlugField and improve that, or send PR's upstream to django-extensions directly.  The license on this project really screwed me up for the next few days...

**Comment by danniranderis** [comment]
Okay - I have now transitioned my projects to django-extensions which I already used for other purposes. Their function `django_extensions.db.fields.AutoSlugField` does exactly the same for my projects.

For others reading this thread / project - feel free to move to another app. This one is definitely dead by now (another ~6 months has passed by) and there is other apps out there doing the same.

**Comment by thevaleriemack** [comment]
@danniranderis but no unique_with ... :_(

**Comment by danniranderis** [comment]
Yes - feel free to create an issue/feature-request in their github-project. Maybe it can be added at some point. :-)

I have also seen projects make a move towards awesome-slugify: https://github.com/dimka665/awesome-slugify maybe they have that feature - I'm not sure. Personally i'm not using that in my projects, so I haven't looked for it.

**Comment by neithere** [comment]
Hi all,

Sorry for the delay. The project was half-dead, but I'm going to finalize the transfer to JazzBand now. It may be too late, but let's see.

As for LGPL, I agree to change the license to BSD, but other contributors will have to also agree with that. I'm suggesting to do this after the transfer.

**Comment by justinmayer** [comment]
I’m traveling at the moment. I’d be happy to assist when I’m a bit more settled.

**Comment by justinmayer** [comment]
It’s more than just traveling... It’s a full-blown relocation. Hopefully will be more settled soon.

**Comment by nim65s** [comment]
Hi :)

This is a friendly reminder that this last "soon" was 2 month ago ;)

**Comment by justinmayer** [comment]
Apologies for the delay, folks. Django 2.x support has been merged via https://github.com/justinmayer/django-autoslug/commit/4dc75083d84265e019a900d636273c731457193d.
