### ISSUE TITLE
ModuleNotFoundError: No module named 'django.core.urlresolvers' on python 3.6.3

### ISSUE THREAD

**Issue by sadaf2605** [justinmayer/django-autoslug#39]
```
File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/autoslug/__init__.py", line 11, in <module>
    from autoslug.fields import AutoSlugField
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/autoslug/fields.py", line 29, in <module>
    from autoslug.settings import slugify, autoslug_modeltranslation_enable
  File "/Users/sadafnoor/.pyenv/versions/evaly3.6.3/lib/python3.6/site-packages/autoslug/settings.py", line 61, in <module>
    from django.core.urlresolvers import get_callable
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

**Comment by dilrajsachdev** [comment]
This is with Django 2.0, change 'django.core.urlresolvers' to 'django.urls'

**Comment by jackton1** [comment]
There package isn't updated with Django 2.0 

```
try:
    from django.core.urlresolvers import get_callable
except ModuleNotFoundError:
   from django.core.urls import get_callable

```

**Comment by barseghyanartur** [comment]
Use https://github.com/iplweb/django-autoslug-iplweb

**Comment by marcosschroh** [comment]
I am getting the same error with django 2.0.5

**Comment by iMerica** [comment]
Using `django-autoslug-iplweb==1.9.4` with Python 3.6.6 + Django 2.1.1 worked for me. Thanks @barseghyanartur.

**Comment by sandeepimpressads** [comment]
Please release the master branch.

**Comment by justinmayer** [comment]
django-autoslug v1.9.4, which should now support Django 1.10, 1.11, and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). The documentation will be updated once ownership of the corresponding ReadTheDocs project has been transferred. ([Link to transfer request](https://github.com/rtfd/readthedocs.org/issues/5216))

Thanks to everyone for your patience! 🎉
