### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jhdulaney** [justinmayer/django-autoslug#49]
Ahoy!  Could you maybe do a new release?

**Comment by ArtemBernatskyy** [comment]
Arrr

**Comment by justinmayer** [comment]
In order to issue a new release, it occurs to me that I would need @neithere to transfer [django-autoslug on PyPI](https://pypi.org/project/django-autoslug/) to me (or at least add me as an admin).

@neithere: Would you be so kind as to make changes in PyPI so I can issue a new release?

**Comment by hammerheadlemon** [comment]
Another thumbs-up from me for getting that new release out. Many thanks!

**Comment by rpkilby** [comment]
If it's appropriate, you may want to look into [PEP 541](https://www.python.org/dev/peps/pep-0541/) to transfer ownership of the package to yourself. You can see some proposals [here](https://github.com/pypa/warehouse/issues?q=label%3A%22PEP+541%22).

**Comment by justinmayer** [comment]
I have [requested ownership](https://github.com/pypa/warehouse/issues/5088) of the `django-autoslug` package on PyPI and will issue a release as soon as the transfer has been completed.

**Comment by ulgens** [comment]
@justinmayer Is there any progress with transfer?

**Comment by ulgens** [comment]
I think i can say congrats now :slightly_smiling_face:

**Comment by jhdulaney** [comment]
You're welcome.

**Comment by jhdulaney** [comment]
Bumping because the issue preventing release has been resolved.

**Comment by justinmayer** [comment]
Hi folks. I made a bunch of commits this morning in preparation for the next release, which I expect to happen within a few days.

**Comment by justinmayer** [comment]
django-autoslug v1.9.4, which should now support Django 1.11 and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). The documentation will be updated once ownership of the corresponding ReadTheDocs project has been transferred. ([Link to transfer request](https://github.com/rtfd/readthedocs.org/issues/5216))

Thanks to everyone for your patience! 🎉
