### ISSUE TITLE
u"Key 'slug' not found in 'CategoryForm'"

### ISSUE THREAD

**Issue by johnsmeeth** [justinmayer/django-autoslug#5]
Dear sir. I just install django-autoslug but when i start add new item on admin panel an error occurred with info: 

KeyError at /admin/blog/category/add/

u"Key 'slug' not found in 'CategoryForm'"

Request Method:     GET
Request URL:    http://localhost:8000/admin/blog/category/add/
Django Version:     1.8.6
Exception Type:     KeyError
Exception Value:    

u"Key 'slug' not found in 'CategoryForm'"

Please help me.
Many thanks

**Comment by iaa** [comment]
Remove ```prepopulated_fields``` from ```CategoryAdmin```

**Comment by johnsmeeth** [comment]
@iaa thanks

**Comment by justinmayer** [comment]
Considering this issue resolved. If that is not the case, please comment here and I will re-open.
