### ISSUE TITLE
Support for Django 2.1.x

### ISSUE THREAD

**Issue by fandrefh** [justinmayer/django-autoslug#50]
I got this error **ImportError: No module named 'django.core.urlresolvers**'

**Comment by sirex** [comment]
This was already fixed, but new version of django-autoslug was not yet released: https://github.com/justinmayer/django-autoslug/pull/46

@justinmayer  could you please release new version of django-autoslug, with this fix?

**Comment by justinmayer** [comment]
@sirex: I just realized that I don't have access to django-autoslug on PyPI, so [I asked @neithere](https://github.com/justinmayer/django-autoslug/issues/49#issuecomment-416552564) if that could be rectified.

**Comment by folt** [comment]
through the pip installs the version that produces an error

**Comment by javipalanca** [comment]
no news from @neithere yet?

**Comment by bronte2k7** [comment]
Maybe just an alias name for the package?

**Comment by nim65s** [comment]
@bronte2k7 if you can't wait for @neithere to hand over the PyPI access to @justinmayer , and would prefer an alias, you can use https://github.com/iplweb/django-autoslug-iplweb with `pip install django-autoslug-iplweb` for now. 
Or, yes, @justinmayer could make an alias too, but I'm not sure this is worth it for now.

**Comment by ulgens** [comment]
Any progress? @neithere @justinmayer :cry:

**Comment by angvp** [comment]
LOL, I think we just have to face the reality that the project is abandoned.

**Comment by justinmayer** [comment]
I have [requested ownership](https://github.com/pypa/warehouse/issues/5088) of the `django-autoslug` package on PyPI and will issue a release as soon as the transfer has been completed.

**Comment by lfalvarez** [comment]
ahha I was having the same problem! apparently I'm going to try with installing the package from github directly. Great work guys BTW!

**Comment by mawkee** [comment]
👀

**Comment by justinmayer** [comment]
django-autoslug v1.9.4, which should now support Django 1.11 and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). The documentation will be updated once ownership of the corresponding ReadTheDocs project has been transferred. ([Link to transfer request](https://github.com/rtfd/readthedocs.org/issues/5216))

Thanks to everyone for your patience! 🎉
