### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by MattFisher** [justinmayer/django-autoslug#6]
`autoslug.utils.get_uniqueness_lookups` uses `_meta.get_field_by_name`, which is deprecated in Django 1.9 and removed in Django 1.10 (shows up when running Django 1.8 with the -Wall python flag):

```
.../python2.7/site-packages/autoslug/utils.py:119: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'
    field_object, model, direct, m2m = instance._meta.get_field_by_name(field_name)
```

**Comment by barseghyanartur** [comment]
What's the status of this?

**Comment by pydanny** [comment]
Resolved in #16, just waiting for commentary or merge by project owner.

**Comment by jpic** [comment]
Can we close this issue now ?

**Comment by barseghyanartur** [comment]
@jpic:

I'd say, it's fixed when a new version containing the fix is released. Asking people to use master branch or certain commit it dirty.

**Comment by edu2004eu** [comment]
@neithere any news on this? This is really breaking Django 1.10+ compatibility. I get that you're busy on other stuff, so is there anyone else with enough privileges that can create the new version?

**Comment by justinmayer** [comment]
django-autoslug v1.9.4, which should now support Django 1.10, 1.11, and 2.0+, has been [released](https://github.com/justinmayer/django-autoslug/releases/tag/v1.9.4) and [published to PyPI](https://pypi.org/project/django-autoslug/). The documentation will be updated once ownership of the corresponding ReadTheDocs project has been transferred. ([Link to transfer request](https://github.com/rtfd/readthedocs.org/issues/5216))

Thanks to everyone for your patience! 🎉
